In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Data

In [5]:
dataset = pd.read_csv('kc_house_data.csv')

In [3]:
dataset.shape

(21613, 21)

In [4]:
dataset.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [5]:
dataset.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

# Preparing the Data - Test Train

In [6]:
dataset.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [6]:
X = dataset[[ 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated',
       'lat', 'long', 'sqft_living15', 'sqft_lot15']]

y = dataset['price']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(15129, 17)
(15129,)
(6484, 17)
(6484,)

In [40]:
X_train

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
1468,4,1.50,1390,7200,1.0,0,0,3,7,1140,250,1965,0,47.7224,-122.332,1630,7702
15590,3,1.50,1450,7316,1.0,0,0,3,7,1450,0,1961,0,47.7725,-122.349,1440,7316
18552,5,2.75,2860,5379,2.0,0,0,3,9,2860,0,2005,0,47.7082,-122.104,2980,6018
10535,2,1.00,1050,4125,1.0,0,0,4,7,1050,0,1909,0,47.5736,-122.307,1650,4125
1069,2,1.00,1240,57000,1.0,0,0,3,7,1240,0,1962,0,47.5970,-122.059,3050,25545
9287,2,1.50,1860,5100,1.0,0,0,3,7,1060,800,1940,0,47.5573,-122.392,1710,5100
12840,3,2.50,2070,7200,2.0,0,0,3,8,2070,0,2001,0,47.6946,-122.211,1650,8877
1759,4,2.50,2710,12138,1.0,0,0,3,8,1700,1010,1968,0,47.7657,-122.290,2390,10052
13495,4,1.75,2030,7350,1.0,0,0,3,8,2030,0,1966,0,47.6274,-122.094,2000,7998
18905,3,1.00,1000,7800,1.0,0,0,4,6,860,140,1930,0,47.7098,-122.283,1700,7800
6718,4,2.50,2730,4385,2.0,0,0,3,8,2730,0,2001,0,47.5975,-122.038,2670,4644
20100,4,2.50,1714,3080,2.0,0,0,3,8,1714,0,2009,0,47.4290,-122.188,1714,3250
21607,3,2.50,1310,1294,2.0,0,0,3,8,1180,130,2008,0,47.5773,-122.409,1330,1265
18053,2,1.75,1240,4120,1.0,0,0,4,7,890,350,1906,0,47.6689,-122.314,1640,3740
15329,2,1.00,1070,6000,1.0,0,0,4,5,1070,0,1922,0,47.4950,-122.227,1910,6000
6344,4,1.00,1480,12675,1.5,0,0,4,7,1480,0,1929,0,47.7630,-122.342,1820,7995
11981,4,1.75,2120,4000,1.5,0,0,4,8,1920,200,1929,0,47.6601,-122.275,2300,4000
19248,4,2.50,1900,8282,1.0,0,0,3,7,1900,0,1968,1997,47.2089,-122.003,1420,8350
4301,5,2.50,2410,15300,1.0,0,0,4,8,1400,1010,1975,0,47.5416,-122.231,2440,15300
6353,4,1.75,1610,9652,1.0,0,0,5,7,1610,0,1969,0,47.3281,-122.135,1220,9800
6946,3,2.50,2420,7500,1.0,0,2,4,8,1210,1210,1944,0,47.6949,-122.389,2340,7500
8899,3,2.25,2800,17300,1.0,0,0,4,8,1420,1380,1971,0,47.5716,-122.128,2140,12650
3057,3,1.50,1620,9310,1.0,0,0,4,7,1620,0,1967,0,47.3665,-122.107,1610,10640
3935,4,2.25,1500,5393,2.0,0,0,3,7,1500,0,1999,0,47.3378,-122.262,1500,5952
12819,3,1.00,1270,7153,1.0,0,0,5,6,1270,0,1949,0,47.4815,-122.226,1650,7153
17714,3,1.75,1500,7560,1.0,0,0,3,7,1500,0,1979,0,47.3467,-122.296,1500,7560
18839,4,2.50,1810,4871,2.0,0,0,3,8,1810,0,1999,0,47.4088,-122.192,1850,5003
5186,4,2.50,2980,4930,2.0,0,0,3,9,2890,90,2000,0,47.5445,-122.120,2980,6099
1465,3,3.25,3190,5283,2.0,0,0,3,9,3190,0,2007,0,47.5534,-122.002,2950,5198
10930,5,2.50,2750,12350,2.0,0,0,3,8,2750,0,1987,0,47.4190,-122.206,1650,9810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871,4,2.00,2460,5921,1.0,0,0,4,7,1230,1230,1948,0,47.3080,-122.209,1260,6648
18430,3,2.00,1010,12252,1.0,0,0,3,8,1010,0,1980,0,47.6224,-122.045,1840,11497
7877,4,1.00,1460,3840,1.5,0,0,3,8,1340,120,1928,0,47.5330,-122.347,990,4200
4851,5,3.25,4115,7910,2.0,0,0,3,9,4115,0,2014,0,47.6847,-122.016,3950,6765
5072,3,2.50,2060,8778,1.0,0,0,3,8,1160,900,1953,2010,47.5245,-122.384,1990,7560
2163,3,3.50,1460,1021,2.0,0,0,3,8,1150,310,2006,0,47.6169,-122.309,1460,1245
6036,4,1.75,1520,5250,1.0,0,0,3,6,1520,0,1949,0,47.6581,-122.390,1530,5250
6921,2,1.00,860,7204,1.0,0,0,3,7,860,0,1918,0,47.5361,-122.351,1200,7500
6216,3,1.00,1380,7470,1.0,0,0,5,7,1380,0,1965,0,47.7479,-122.343,1440,7473
16921,2,1.00,1100,7500,1.0,0,0,3,7,1100,0,1951,0,47.7235,-122.326,1920,7149
2897,4,2.00,2030,4033,2.0,0,0,4,7,1630,400,1925,0,47.7056,-122.342,1350,1340
18606,4,3.00,2860,10292,1.0,0,0,4,8,2860,0,1953,1999,47.6286,-122.206,1840,10273
10327,3,2.25,1880,6565,1.0,0,0,4,8,1420,460,1972,0,47.6396,-122.113,2060,7280
18983,3,2.00,1350,8960,1.0,0,0,4,7,1350,0,1986,0,47.3614,-122.045,1470,8288
17089,3,2.25,2130,11782,1.0,0,0,4,8,1590,540,1977,0,47.5423,-122.215,2700,11782
14650,4,3.00,2530,5625,1.0,0,0,3,8,1470,1060,1976,0,47.7094,-122.233,1840,7070
19852,4,3.50,3150,6202,2.0,0,0,3,7,3150,0,2005,0,47.3993,-122.162,2950,5940
6744,3,1.00,1620,5040,1.0,0,0,3,7,1120,500,1964,0,47.5263,-122.286,1790,6178
15832,4,2.50,2080,7000,1.0,0,0,4,8,1400,680,1989,0,47.4252,-122.163,2090,7082
15430,4,3.75,3490,5625,2.0,0,0,3,9,2610,880,2014,0,47.6685,-122.332,1940,5000
14935,2,1.00,1320,1824,1.5,0,0,4,6,1320,0,1909,0,47.5850,-122.294,1320,4000
14116,3,1.75,2130,4400,1.0,0,0,3,7,1430,700,1922,0,47.6417,-122.325,1710,3300
20757,3,2.00,2360,6145,1.0,0,0,3,8,2360,0,2011,0,47.3564,-122.198,2304,5880
9225,3,1.75,1480,4800,2.0,0,0,4,7,1140,340,1944,0,47.6567,-122.397,1810,4800
21243,4,3.00,3640,5096,2.0,0,0,3,8,2740,900,2010,0,47.5428,-122.270,1910,9189
13123,5,5.00,3960,94089,2.0,0,0,3,10,3960,0,1998,0,47.3800,-122.011,2240,64468
19648,2,2.50,1400,1262,2.0,0,0,3,8,1160,240,2008,0,47.5342,-122.349,1060,1524
9845,3,2.25,2360,14950,1.0,0,0,4,9,2360,0,1978,0,47.3856,-122.158,2720,14388
10799,4,2.00,2370,76665,2.0,0,0,4,8,2370,0,1978,0,47.2831,-122.279,2110,19334
2732,4,2.25,2380,16236,1.0,0,0,3,7,1540,840,1961,0,47.6126,-122.120,2230,8925

# Training

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

# Making the Predictions

In [9]:
y_pred = regressor.predict(X_test)

In [43]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

          Actual     Predicted
17384   297000.0  3.872015e+05
722    1578000.0  1.502715e+06
2680    562100.0  5.274534e+05
18754   631500.0  5.779358e+05
14554   780000.0  9.993390e+05
16227   485000.0  3.715189e+05
6631    340000.0  4.023946e+05
19813   335606.0  4.033902e+05
3367    425000.0  5.762415e+05
21372   490000.0  1.204649e+06
3268    732000.0  6.933285e+05
20961   389700.0  3.649199e+05
21456   450000.0  3.721866e+05
3880    357000.0  3.133158e+05
17472   960000.0  8.369357e+05
7618    257000.0  4.064371e+05
1091    448000.0  3.373915e+05
1560    610000.0  6.626157e+05
8945    230950.0  3.204135e+05
8439    377500.0  5.608255e+05
13058   375000.0  3.574085e+05
12080   410000.0  3.924029e+05
7417    459000.0  6.422665e+05
3101    190000.0  2.066109e+05
18769   585000.0  6.023814e+05
7332    280000.0  2.775805e+05
19186   500000.0  4.671493e+05
11875   465000.0  6.062019e+05
14100   802000.0  9.102067e+05
10641   440000.0  4.991178e+05
...          ...           ...
5838    980000.0  8.682346e+05
17350   520000.0  5.535546e+05
17675   325000.0  5.882351e+05
3572    770000.0  4.600046e+05
16888   995000.0  1.507666e+06
21433   465750.0  6.943522e+05
18026   575000.0  4.904745e+05
6588    425000.0  4.311267e+05
11504   398500.0  5.724323e+05
530     270500.0  2.557042e+05
4897    310000.0  2.732955e+05
9185    190000.0  1.635641e+05
13245   492000.0  6.037054e+05
4264    235000.0  2.869653e+05
7673    765000.0  9.725420e+05
13167   530000.0  5.341991e+05
21174   525000.0  7.070123e+05
16924   226000.0  3.611855e+05
19310   624000.0  6.310279e+05
1916    500000.0  4.989723e+05
15231   467500.0  5.149869e+05
8210    203000.0  2.544291e+05
12860   446000.0  4.133758e+05
12947   206000.0  1.677126e+05
21490   529000.0  6.580611e+05
18588  1100000.0  4.674270e+05
6784    700000.0  5.367858e+05
14510   380000.0  3.258294e+05
18917   268000.0  2.033599e+05
11750   206000.0  1.617831e+05

[6484 rows x 2 columns]

# Evaluating the Algorithm

In [10]:
from sklearn import metrics

print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_pred))

print('Mean Squared Error: ', metrics.mean_squared_error(y_test, y_pred))

print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error:  125002.07442243666
Mean Squared Error:  43690646677.92305
Root Mean Squared Error:  209023.07690282204